### ISSUE TITLE
BASALT results on other camera models

### ISSUE THREAD

**Issue by Aishkrish18** [kwang-12/ros_basalt#1]
Can basalt only work on T265 or is it possible to set it up for cameras like azure kinect/ ZED2 stereo cameras and D455 realsense? 
I am working on my thesis to test some open localization methods and I would like to know a little in detail about this to try out this algorithm. 
Thanks :)

**Comment by kwang-12** [comment]
Currently this repo consists of code that works with realsense T265 out of box. 
Take a look at the code in [scripts/rs_t265_vio.cpp](https://github.com/kwang-12/ros_basalt/blob/a0d2471614a5a78725446d4370eea8b95cbc86e8/scripts/rs_t265_vio.cpp#L36C1-L38C26) for the initialization of the camera.

For this project to work with cameras other than T265, you will need to implement your own hardware interfacing code to get the images and IMU data from the camera so they can be processed. 

Also take a look at how the camera calibration data are handled in [src/basalt/device/rs_t265.cpp](https://github.com/kwang-12/ros_basalt/tree/main/src/ros_basalt/device/rs_t265.cpp)
